name: Dev & Prod Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  code_build_and_tests:
    runs-on: ubuntu-latest
    name: Code Build and Tests
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests
      run: dotnet test --configuration release

  build_image:
    name: Build Image and Push to ACR
    needs: [code_build_and_tests]
    runs-on: ubuntu-latest
    env:
      APP_FOLDER: HelloWorldApi
      IMAGE_NAME: "${{ vars.ACR_SERVER }}/${{ vars.ACR_IMAGE_NAME }}"

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ vars.ACR_SERVER }}
        username: ${{ vars.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push in Azure ACR
      run: |
        docker build . --file ./${{ env.APP_FOLDER }}/Dockerfile --tag ${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
        docker tag ${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER ${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.IMAGE_NAME }}

  development_deploy:
    name: Dev Deployment
    environment: development
    runs-on: ubuntu-latest
    needs: [ build_image ]
    env:
      WEB_APP:  ${{ vars.AZURE_WEBAPP_NAME }}

    steps:
      - name: Azure login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Web App Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEB_APP }}
          images: ${{ secrets.IMAGE_NAME }}:latest

  production_deploy:
    name: 'Production Deployment'
    environment: production
    runs-on: ubuntu-latest
    needs: [ development_deploy ]
    env:
      WEB_APP: ${{ vars.AZURE_WEBAPP_NAME }}

    steps:
      - name: Azure login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Web App Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEB_APP }}
          images: ${{ secrets.IMAGE_NAME }}:latest
